// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tema.Data;

#nullable disable

namespace tema.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241021162748_SeedGenderTabel")]
    partial class SeedGenderTabel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tema.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SrDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlDescription = "Femer",
                            EnDescription = "Female",
                            SrDescription = "Zensko"
                        },
                        new
                        {
                            Id = 2,
                            AlDescription = "Mashkull",
                            EnDescription = "Male",
                            SrDescription = "Muski"
                        },
                        new
                        {
                            Id = 3,
                            AlDescription = "Te tjera",
                            EnDescription = "Others",
                            SrDescription = "Drugi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
